---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fediverse
resources:
  - ./cluster.yaml
  - ./externalsecret.yaml
  - ./scheduledbackup.yaml
  - ./prometheusrule.yaml
  # - ./service.yaml
